name: CoStrength
version: 1.0
main: io.github.thelordman.costrength.CoStrength
api-version: 1.18
authors: [The Lord#8349, Harfang#4149]
description: The main plugin used by CoStrength. costrength.minehut.gg | https://discord.gg/EDvrURNDa4
website: thelordman.github.io
load: STARTUP
default-permission: op
commands:
  gmc:
    description: Changes target's gamemode to creative.
    usage: /gmc [player]
  gms:
    description: Changes target's gamemode to survival.
    usage: /gms [player]
  gma:
    description: Changes target's gamemode to adventure.
    usage: /gma [player]
  gmsp:
    description: Changes target's gamemode to spectator.
    usage: /gmsp [player]
  liami:
    description: Say something as Liami, even if he's offline.
    usage: /liami [text]
  balance:
    description: Check the balance of an offline or online player.
    aliases: bal
    usage: /bal [offline-player]
  economy:
    description: Change or get various values about the target's economy.
    aliases: [eco, econ]
    usage: /eco <offline-player> <set, add, remove, reset, multiply, divide, get, pow> [<amount>]
  stats:
    description: Check the stats of an offline or online player.
    aliases: st
    usage: /stats [offline-player]
  jail:
    description: Send or release a player to or from jail, or set the location of jail.
    aliases: j
    usage: /jail [offline-player]
  sun:
    description: Set the weather to sunny.
    aliases: [clean, clouds]
    usage: /sun
  rain:
    description: Set the weather to rain.
    aliases: [snow, downfall]
    usage: /rain
  thunder:
    description: Set the weather to thunder.
    aliases: storm
    usage: /thunder
  broadcast:
    description: Send a broadcast accross the server and in Discord.
    aliases: bc
    usage: /broadcast <text>
  spawn:
    description: Send someone or yourself to spawn.
    usage: /spawn [player]
  tphere:
    description: Teleports the target to the location of the executor.
    usage: /tphere <player>
  commandspy:
    description: Toggle Command Spy on and off. While toggled on, you can see all executed commands by everyone.
    aliases: [cmdspy, cspy]
    usage: /commandspy
  rank:
    description: Give any online player any rank.
    usage: /rank <offline-player> set <rank>
  help:
    description: Link to the wiki.
    usage: /help
  discord:
    description: Link to the Discord server.
    aliases: dc
    usage: /discord
  mine:
    description: Reset the mine.
    aliases: m
    usage: /mine
  bounty:
    description: Set or check a player's bounty.
    usage: /bounty [player] [amount]
  stal:
    description: stal
    usage: /stal [player]
  enderchest:
    description: Access your's or someone else's enderchest.
    aliases: ec
    usage: /ec [player]
  donator:
    description: View the permissions and commands of donator ranks.
    aliases: donor
    usage: /donor
  joinkit:
    description: Give an online player the default kit.
    usage: /joinkit [player]
  level:
    description: Change or get various values about the target's level.
    usage: /level <offline-player> <set, add, remove, reset, multiply, divide, get, pow> [<amount>]
  glow:
    description: Add or remove glowing to yourself.
    usage: /glow